version: "3"

services:
  mongo1:
    container_name: mongo1
    image: mongo:${MONGODB_VERSION:-4.4}
    restart: always
    volumes:
      - ./volumes/mongodb1:/data/db
    ports:
      #- "${MONGO_IP:127.0.0.1}:27011:27011"
      - 27011:27011
    expose:
      - "27011"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--port", "27011",
        "--replSet", "rs0",
        "--bind_ip_all",
	"--auth",
	"--keyFile", "/data/db/mongodb.key",
      ]

  mongo2:
    container_name: mongo2
    image: mongo:${MONGODB_VERSION:-4.4}
    restart: always
    volumes:
      - ./volumes/mongodb2:/data/db
    ports:
      #- "${MONGO_IP:127.0.0.1}:27012:27012"
      - 27012:27012
    expose:
      - "27012"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--port", "27012",
        "--replSet", "rs0",
        "--bind_ip_all",
	"--auth",
        "--keyFile", "/data/db/mongodb.key",
      ]

  mongo3:
    container_name: mongo3
    image: mongo:${MONGODB_VERSION:-4.4}
    restart: always
    volumes:
      - ./volumes/mongodb3:/data/db
      - ./volumes/config:/config
    ports:
      #- "${MONGO_IP:127.0.0.1}:27013:27013"
      - 27013:27013
    expose:
      - "27013"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--port", "27013",
        "--replSet", "rs0",
        "--bind_ip_all",
	"--auth",
        "--keyFile", "/data/db/mongodb.key",
      ]

  mongosetup:
    container_name: mongosetup
    image: "mongo-setup"
    build: "./"
    depends_on:
      - mongo1

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://devadmin:2i7cTAJAs2uv2JuqD9pR@mongo1:27011,mongo2:27012,mongo3:27013/?replicaSet=rs0
    ports:
      - "${MONGOEXPRESS_IP:-127.0.0.1}:8081:8081"
    restart: always
    depends_on:
      - mongo1
      - mongosetup

networks: 
  default: 
    external: 
      name: internal-network
